pushed branch
Hammond1979/propertypro pull request #3
Opened 2022-02-04 12:51 UTC by Hammond1979

2022-02-04 14:06 UTC, mykelmatics reviewed
This really looking good so far, just for few changes I think all will be okay, but the PR naming should also be worked on

2022-02-04 14:06 UTC, mykelmatics commented on src/component/Properties/Property.jsx
> +                <div className='propertyCard'>
I suggest you change the "proper" to a more detailed naming, maybe "eachProperty"

2022-02-04 14:06 UTC, mykelmatics commented on src/component/Registration/SignIn.jsx
>             <section className='registrationWrapper'>
I didn't see the closing tagof this section

2022-02-04 14:06 UTC, mykelmatics commented on src/component/Registration/Signup.css
> +
Try to remove commented line

2022-02-07 06:22 UTC, Shukura2 requested changes
Nice work.

2022-02-07 06:22 UTC, Shukura2 commented on src/component/Registration/SignIn.jsx
> +                <form action="" className="signinForm">
Lets take out the action for now, since its not in use

2022-02-07 06:22 UTC, Shukura2 commented on src/component/Registration/SignIn.jsx
> +                        <input type="Password" id='name' name='Password' />
Is it not necessary for this to have a place holder? If yes, lets add it. Please add for other input field also.

2022-02-07 06:22 UTC, Shukura2 commented on src/component/Registration/SignIn.jsx
> +                        <label htmlfor=""> Remember Me</label>
lets add the value for htmlFor

2022-02-08 10:48 UTC, Shukura2 approved these changes

2022-02-08 11:05 UTC, nosisky commented on src/App.js
> +          <Route path='/propertydetails' element={<PropertyDetails />} />
```suggestion
          <Route path='/property-details' element={<PropertyDetails />} />
```

2022-02-08 12:58 UTC, merged